### ISSUE TITLE
Listener creation fails due to service name length exceeding 63 characters

### ISSUE THREAD

**Issue by blafry** [glothriel/wormhole#85]
## Description

When attempting to create a listener, the service name validation fails because the name exceeds the Kubernetes character limit of 63 characters. The error message returned is as follows:

```
time="2024-11-19T14:42:15Z" level=error msg="Could not create listener: Service \"dawn-king-ehk-blaafryy-consul-devenv-consul-headless-serflan-tcp\" is invalid: metadata.name: Invalid value: \"dawn-king-ehk-blaafryy-consul-devenv-consul-headless-serflan-tcp\": must be no more than 63 characters"
```

Affected service:

```
apiVersion: v1
kind: Service
metadata:
  name: devenv-consul-headless
  namespace: "blaafryy-consul"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      protocol: TCP
      port: 8500
    - name: rpc
      port: 8400
    - name: serflan-tcp
      protocol: TCP
      port: 8301
    - name: serflan-udp
      protocol: UDP
      port: 8301
    - name: rpc-server
      port: 8300
    - name: dns-tcp
      port: 8600
    - name: dns-udp
      protocol: UDP
      port: 8600
  selector:
    app.kubernetes.io/instance: devenv
    app.kubernetes.io/name: consul
  sessionAffinity: None
```
